### ISSUE TITLE
Not responsive Extension issue

### ISSUE THREAD

**Issue by lifefocus79** [yakimovim/vscode-check-npm-updates#11]
- Issue Type: `Bug`
- Extension Name: `check-npm-updates`
- Extension Version: `1.7.7`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by yakimovim** [comment]
I don't understand what the problem is. What does it mean "not responsive"? How does it look like?
