### ISSUE TITLE
Feature update: Support for Python's requirements.txt file equivalent to package.json

### ISSUE THREAD

**Issue by peterpoliwoda** [yakimovim/vscode-check-npm-updates#12]
Hi Ivan,
First of all, I'd like to say that I've been working with your npm updates plugin for some time now and I'm really loving it! Thank you for making my life and many other developers easier by putting this together! 

Recently, I have started working on a python project which uses the standard `requirements.txt` file. It sort of works like npm, it's not as good, but you get the picture. Would you ever consider creating a python equivalent for the requirements.txt or an upgrade to your current version of the plugin to also check for updates at pypi.org as well as npmjs.com?

Thanks again for being such a good sport!

**Comment by yakimovim** [comment]
Hello, Peter,

Thank you for your appreciation of my product.

The problem with Python package manager is that I am not familiar enough with Python. But the general idea is great. There is nothing preventing us from working with different package managers and languages.

But this will be implemented in a separate VS Code extension, as the name of this extension ('check-npm-updates') suggests that it works only with NodeJS.
