### ISSUE TITLE
Add the ability to ignore certain packages

### ISSUE THREAD

**Issue by ReallyNotARussianSpy** [yakimovim/vscode-check-npm-updates#2]
For example, in my Angular project, I do not want to upgrade to the latest TypeScript version, because that new version is not supported by Angular.

**Comment by yakimovim** [comment]
Thank you for your suggestion. I have added support of configuration file `.checkNpmUpdates.json` for each folder with `package.json`. In this file, you can specify packages you want to ignore. You even can disable check of updates for this folder entirely. See `README.md` for details.
