### ISSUE TITLE
Checks for bower updates and incorrectly reports them as outdated

### ISSUE THREAD

**Issue by zenopopovici** [yakimovim/vscode-check-npm-updates#3]
![screenshot 2018-10-12 at 09 58 48](https://user-images.githubusercontent.com/767998/46852988-7ea98f80-ce05-11e8-8a0f-4663a10a89b0.png)

Can we ignore bower_components?

**Comment by yakimovim** [comment]
Do I understand you right, that you want to exclude some folders (in your case "bower_components") from checking for updates in "package.json" files?

**Comment by zenopopovici** [comment]
Hello, 

Yes, It shouldn't check `bower_components` folder at all. It should check only `node_modules` folder. 
Right now it confuses bower packages with node packages and generates false alerts.

Thanks.

**Comment by yakimovim** [comment]
Done.

**Comment by zenopopovici** [comment]
Thanks!

**Comment by zenopopovici** [comment]
Worsk perfectly. Thanks a lot!!!
