### ISSUE TITLE
Feature: Highlight packages

### ISSUE THREAD

**Issue by MoKhajavi75** [yakimovim/vscode-check-npm-updates#6]
Hey

Thanks for your efforts!
I want to suggest one new feature which is to highlight packages (in package,json) which need an update!

I guess it would be much much easier to see updates rather than notifications.

:heart:

**Comment by yakimovim** [comment]
Thank you!

Why don't you use something like Version Lens extension to highlight possible updates in package.json?

**Comment by MoKhajavi75** [comment]
I didn't hear about `Version Lens` 😁
Thanks!
